name: Annoyer
main: org.kitteh.annoyer.Annoyer
version: 2.1
author: mbaxter
description: Annoy your enemies!
commands:
  annoy:
    Description: Pester a player
    Usage: /annoy <name>
  unannoy:
    Description: Stop pestering a player
    Usage: /unannoy <playername>